[build]
target = "x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-no-pie",
  "-C", "link-arg=-Wl,-e,_start",
  "-C", "link-arg=-static",
  "-C", "link-arg=-Wl,--build-id=none",
]
